local client = vim.lsp.get_clients()[2]
print(client.supports_method('callHierarchy/incomingCalls'), 'callHierarchy/incomingCalls')
print(client.supports_method('callHierarchy/outgoingCalls'), 'callHierarchy/outgoingCalls')
print(client.supports_method('textDocument/codeAction'), 'textDocument/codeAction')
print(client.supports_method('textDocument/completion'), 'textDocument/completion')
print(client.supports_method('textDocument/declaration'), 'textDocument/declaration')
print(client.supports_method('textDocument/definition'), 'textDocument/definition')
print(client.supports_method('textDocument/diagnostic'), 'textDocument/diagnostic')
print(client.supports_method('textDocument/documentHighlight'), 'textDocument/documentHighlight')
print(client.supports_method('textDocument/documentSymbol'), 'textDocument/documentSymbol')
print(client.supports_method('textDocument/foldingRange'), 'textDocument/foldingRange')
print(client.supports_method('textDocument/formatting'), 'textDocument/formatting')
print(client.supports_method('textDocument/hover'), 'textDocument/hover')
print(client.supports_method('textDocument/implementation'), 'textDocument/implementation')
print(client.supports_method('textDocument/inlayHint'), 'textDocument/inlayHint')
print(client.supports_method('textDocument/prepareTypeHierarchy'), 'textDocument/prepareTypeHierarchy')
print(client.supports_method('textDocument/publishDiagnostics'), 'textDocument/publishDiagnostics')
print(client.supports_method('textDocument/rangeFormatting'), 'textDocument/rangeFormatting')
print(client.supports_method('textDocument/rangesFormatting'), 'textDocument/rangesFormatting')
print(client.supports_method('textDocument/references'), 'textDocument/references')
print(client.supports_method('textDocument/rename'), 'textDocument/rename')
print(client.supports_method('textDocument/semanticTokens/full'), 'textDocument/semanticTokens/full')
print(client.supports_method('textDocument/semanticTokens/full/delta'),
	'texclient/full/delta')
print(client.supports_method('textDocument/signatureHelp'), 'textDocument/signatureHelp')
print(client.supports_method('textDocument/typeDefinition*'), 'textDocument/typeDefinition*')
print(client.supports_method('typeHierarchy/subtypes'), 'typeHierarchy/subtypes')
print(client.supports_method('typeHierarchy/supertypes'), 'typeHierarchy/supertypes')
print(client.supports_method('window/logMessage'), 'window/logMessage')
print(client.supports_method('window/showMessage'), 'window/showMessage')
print(client.supports_method('window/showDocument'), 'window/showDocument')
print(client.supports_method('window/showMessageRequest'), 'window/showMessageRequest')
print(client.supports_method('workspace/applyEdit'), 'workspace/applyEdit')
print(client.supports_method('workspace/configuration'), 'workspace/configuration')
print(client.supports_method('workspace/executeCommand'), 'workspace/executeCommand')
print(client.supports_method('workspace/inlayHint/refresh'), 'workspace/inlayHint/refresh')
print(client.supports_method('workspace/symbol'), 'workspace/symbol')
print(client.supports_method('workspace/workspaceFolders'), 'workspace/workspaceFolders')
